# Geant4 >= 11.1 picks a default driver; for older versions use e.g. /vis/open OGL
/vis/open
/vis/drawVolume
/vis/geometry/set/visibility World 0 false
/vis/geometry/set/colour Target 0 0.6 0.6 0.6 0.6
/vis/viewer/set/viewpointThetaPhi 90 90 deg
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/scene/endOfEventAction accumulate 20
/vis/viewer/set/autoRefresh true
